name: Workflow CI

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Run actions/checkout@v3
        uses: actions/checkout@v3
      
      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      - name: Check Env
        run: python --version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow==2.19.0

      - name: Set MLflow Tracking URI
        run: echo "MLFLOW_TRACKING_URI=file:./mlruns" >> $GITHUB_ENV

      - name: Run MLflow project
        run: mlflow run MLProject --env-manager=local

      - name: Install Python dependencies from conda.yaml
        if: false # optional kalau environment sudah dipasang di langkah awal
        run: |
          echo "skip karena sudah di-handle di env MLflow"

      - name: Upload MLflow artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-artifacts
          path: mlruns/
